services:
  docker:
    image: docker:dind
    privileged: true

pipeline:
  build:
    image: docker
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - echo "Building with alpine:$ALPINE_VERSION"
      - docker build --build-arg VER=$ALPINE_VERSION -t devbuild .

  test:
    image: docker
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - docker run --rm devbuild sh -c 'for b in cmake make gcc g++; do sh -eaxc "$b --version"; done'

  publish:
    image: docker
    secrets: [ DOCKER_USER, DOCKER_PASS ]
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
      - docker tag devbuild frebib/alpine-cmake:$ALPINE_VERSION
      - docker push frebib/alpine-cmake

matrix:
  ALPINE_VERSION:
    - 3.4
    - 3.5
    - 3.6
    - latest
