pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo "Building with alpine:$TAG"
      - docker build --build-arg VER=$TAG -t frebib/alpine-cmake:$TAG .

  test:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker run --rm frebib/alpine-cmake:$TAG 
            sh -c 'for b in cmake make gcc g++; do sh -eaxc "$b --version"; done'

  publish:
    image: docker
    secrets: [ DOCKER_USER, DOCKER_PASS ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
      - docker push frebib/alpine-cmake:$TAG

matrix:
  TAG:
    - 3.4
    - 3.5
    - 3.6
    - 3.7
    - latest
